[phases.setup]
aptPkgs = [
  "libgl1",
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxext6",
  "libxrender1"
]
nixPkgs = [
  "libGL",
  "glib",
  "xorg.libSM",
  "xorg.libXext",
  "xorg.libXrender"
]
